//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaIntegracion.ServicioProducto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaField;
        
        private decimal PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CapaIntegracion.ServicioProducto.Imagenes[] ImágenesField;
        
        private int StockField;
        
        private double calificacionField;
        
        private System.DateTime FechaDeCreacionField;
        
        private System.DateTime FechaUltimaModificacionField;
        
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenPrincipalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public CapaIntegracion.ServicioProducto.Imagenes[] Imágenes {
            get {
                return this.ImágenesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImágenesField, value) != true)) {
                    this.ImágenesField = value;
                    this.RaisePropertyChanged("Imágenes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double calificacion {
            get {
                return this.calificacionField;
            }
            set {
                if ((this.calificacionField.Equals(value) != true)) {
                    this.calificacionField = value;
                    this.RaisePropertyChanged("calificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime FechaDeCreacion {
            get {
                return this.FechaDeCreacionField;
            }
            set {
                if ((this.FechaDeCreacionField.Equals(value) != true)) {
                    this.FechaDeCreacionField = value;
                    this.RaisePropertyChanged("FechaDeCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime FechaUltimaModificacion {
            get {
                return this.FechaUltimaModificacionField;
            }
            set {
                if ((this.FechaUltimaModificacionField.Equals(value) != true)) {
                    this.FechaUltimaModificacionField = value;
                    this.RaisePropertyChanged("FechaUltimaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ImagenPrincipal {
            get {
                return this.ImagenPrincipalField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenPrincipalField, value) != true)) {
                    this.ImagenPrincipalField = value;
                    this.RaisePropertyChanged("ImagenPrincipal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Imagenes", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Imagenes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private int IDPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        private System.DateTime FechaDeAsignacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IDP {
            get {
                return this.IDPField;
            }
            set {
                if ((this.IDPField.Equals(value) != true)) {
                    this.IDPField = value;
                    this.RaisePropertyChanged("IDP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime FechaDeAsignacion {
            get {
                return this.FechaDeAsignacionField;
            }
            set {
                if ((this.FechaDeAsignacionField.Equals(value) != true)) {
                    this.FechaDeAsignacionField = value;
                    this.RaisePropertyChanged("FechaDeAsignacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Task", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CapaIntegracion.ServicioProducto.TaskOfBoolean))]
    public partial class Task : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskOfBoolean", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TaskOfBoolean : CapaIntegracion.ServicioProducto.Task {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioProducto.ServicioProductoSoap")]
    public interface ServicioProductoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento producto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearProducto", ReplyAction="*")]
        CapaIntegracion.ServicioProducto.CrearProductoResponse CrearProducto(CapaIntegracion.ServicioProducto.CrearProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.CrearProductoResponse> CrearProductoAsync(CapaIntegracion.ServicioProducto.CrearProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Remitente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImagenesProducto", ReplyAction="*")]
        CapaIntegracion.ServicioProducto.ImagenesProductoResponse ImagenesProducto(CapaIntegracion.ServicioProducto.ImagenesProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImagenesProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.ImagenesProductoResponse> ImagenesProductoAsync(CapaIntegracion.ServicioProducto.ImagenesProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProductoExiste", ReplyAction="*")]
        CapaIntegracion.ServicioProducto.ProductoExisteResponse ProductoExiste(CapaIntegracion.ServicioProducto.ProductoExisteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProductoExiste", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.ProductoExisteResponse> ProductoExisteAsync(CapaIntegracion.ServicioProducto.ProductoExisteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Remitente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ComandoProductos", ReplyAction="*")]
        CapaIntegracion.ServicioProducto.ComandoProductosResponse ComandoProductos(CapaIntegracion.ServicioProducto.ComandoProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ComandoProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.ComandoProductosResponse> ComandoProductosAsync(CapaIntegracion.ServicioProducto.ComandoProductosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento producto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarProducto", ReplyAction="*")]
        CapaIntegracion.ServicioProducto.ActualizarProductoResponse ActualizarProducto(CapaIntegracion.ServicioProducto.ActualizarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.ActualizarProductoResponse> ActualizarProductoAsync(CapaIntegracion.ServicioProducto.ActualizarProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Remitente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarProducto", ReplyAction="*")]
        CapaIntegracion.ServicioProducto.EliminarProductoResponse EliminarProducto(CapaIntegracion.ServicioProducto.EliminarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.EliminarProductoResponse> EliminarProductoAsync(CapaIntegracion.ServicioProducto.EliminarProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento imagenes del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarImagenProducto", ReplyAction="*")]
        CapaIntegracion.ServicioProducto.AgregarImagenProductoResponse AgregarImagenProducto(CapaIntegracion.ServicioProducto.AgregarImagenProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarImagenProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.AgregarImagenProductoResponse> AgregarImagenProductoAsync(CapaIntegracion.ServicioProducto.AgregarImagenProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Remitente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerImagenesProducto", ReplyAction="*")]
        CapaIntegracion.ServicioProducto.ObtenerImagenesProductoResponse ObtenerImagenesProducto(CapaIntegracion.ServicioProducto.ObtenerImagenesProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerImagenesProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.ObtenerImagenesProductoResponse> ObtenerImagenesProductoAsync(CapaIntegracion.ServicioProducto.ObtenerImagenesProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NombreImagen del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarImagenP", ReplyAction="*")]
        CapaIntegracion.ServicioProducto.EliminarImagenPResponse EliminarImagenP(CapaIntegracion.ServicioProducto.EliminarImagenPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarImagenP", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.EliminarImagenPResponse> EliminarImagenPAsync(CapaIntegracion.ServicioProducto.EliminarImagenPRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearProducto", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioProducto.CrearProductoRequestBody Body;
        
        public CrearProductoRequest() {
        }
        
        public CrearProductoRequest(CapaIntegracion.ServicioProducto.CrearProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaIntegracion.ServicioProducto.Producto producto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public CrearProductoRequestBody() {
        }
        
        public CrearProductoRequestBody(CapaIntegracion.ServicioProducto.Producto producto, string Remitente, int Origen) {
            this.producto = producto;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioProducto.CrearProductoResponseBody Body;
        
        public CrearProductoResponse() {
        }
        
        public CrearProductoResponse(CapaIntegracion.ServicioProducto.CrearProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CrearProductoResult;
        
        public CrearProductoResponseBody() {
        }
        
        public CrearProductoResponseBody(bool CrearProductoResult) {
            this.CrearProductoResult = CrearProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImagenesProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImagenesProducto", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioProducto.ImagenesProductoRequestBody Body;
        
        public ImagenesProductoRequest() {
        }
        
        public ImagenesProductoRequest(CapaIntegracion.ServicioProducto.ImagenesProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImagenesProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public ImagenesProductoRequestBody() {
        }
        
        public ImagenesProductoRequestBody(int id, string Remitente, int Origen) {
            this.id = id;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImagenesProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImagenesProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioProducto.ImagenesProductoResponseBody Body;
        
        public ImagenesProductoResponse() {
        }
        
        public ImagenesProductoResponse(CapaIntegracion.ServicioProducto.ImagenesProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImagenesProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaIntegracion.ServicioProducto.Imagenes[] ImagenesProductoResult;
        
        public ImagenesProductoResponseBody() {
        }
        
        public ImagenesProductoResponseBody(CapaIntegracion.ServicioProducto.Imagenes[] ImagenesProductoResult) {
            this.ImagenesProductoResult = ImagenesProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductoExisteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductoExiste", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioProducto.ProductoExisteRequestBody Body;
        
        public ProductoExisteRequest() {
        }
        
        public ProductoExisteRequest(CapaIntegracion.ServicioProducto.ProductoExisteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoExisteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public ProductoExisteRequestBody() {
        }
        
        public ProductoExisteRequestBody(string nombre, string Remitente, int Origen) {
            this.nombre = nombre;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductoExisteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductoExisteResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioProducto.ProductoExisteResponseBody Body;
        
        public ProductoExisteResponse() {
        }
        
        public ProductoExisteResponse(CapaIntegracion.ServicioProducto.ProductoExisteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoExisteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ProductoExisteResult;
        
        public ProductoExisteResponseBody() {
        }
        
        public ProductoExisteResponseBody(bool ProductoExisteResult) {
            this.ProductoExisteResult = ProductoExisteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComandoProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComandoProductos", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioProducto.ComandoProductosRequestBody Body;
        
        public ComandoProductosRequest() {
        }
        
        public ComandoProductosRequest(CapaIntegracion.ServicioProducto.ComandoProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ComandoProductosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Orden;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public ComandoProductosRequestBody() {
        }
        
        public ComandoProductosRequestBody(int Orden, string Remitente, int Origen) {
            this.Orden = Orden;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComandoProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComandoProductosResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioProducto.ComandoProductosResponseBody Body;
        
        public ComandoProductosResponse() {
        }
        
        public ComandoProductosResponse(CapaIntegracion.ServicioProducto.ComandoProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ComandoProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ComandoProductosResult;
        
        public ComandoProductosResponseBody() {
        }
        
        public ComandoProductosResponseBody(string ComandoProductosResult) {
            this.ComandoProductosResult = ComandoProductosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarProducto", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioProducto.ActualizarProductoRequestBody Body;
        
        public ActualizarProductoRequest() {
        }
        
        public ActualizarProductoRequest(CapaIntegracion.ServicioProducto.ActualizarProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaIntegracion.ServicioProducto.Producto producto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public ActualizarProductoRequestBody() {
        }
        
        public ActualizarProductoRequestBody(CapaIntegracion.ServicioProducto.Producto producto, string Remitente, int Origen) {
            this.producto = producto;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioProducto.ActualizarProductoResponseBody Body;
        
        public ActualizarProductoResponse() {
        }
        
        public ActualizarProductoResponse(CapaIntegracion.ServicioProducto.ActualizarProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarProductoResult;
        
        public ActualizarProductoResponseBody() {
        }
        
        public ActualizarProductoResponseBody(bool ActualizarProductoResult) {
            this.ActualizarProductoResult = ActualizarProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarProducto", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioProducto.EliminarProductoRequestBody Body;
        
        public EliminarProductoRequest() {
        }
        
        public EliminarProductoRequest(CapaIntegracion.ServicioProducto.EliminarProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public EliminarProductoRequestBody() {
        }
        
        public EliminarProductoRequestBody(int Id, string Remitente, int Origen) {
            this.Id = Id;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioProducto.EliminarProductoResponseBody Body;
        
        public EliminarProductoResponse() {
        }
        
        public EliminarProductoResponse(CapaIntegracion.ServicioProducto.EliminarProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EliminarProductoResult;
        
        public EliminarProductoResponseBody() {
        }
        
        public EliminarProductoResponseBody(bool EliminarProductoResult) {
            this.EliminarProductoResult = EliminarProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarImagenProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarImagenProducto", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioProducto.AgregarImagenProductoRequestBody Body;
        
        public AgregarImagenProductoRequest() {
        }
        
        public AgregarImagenProductoRequest(CapaIntegracion.ServicioProducto.AgregarImagenProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarImagenProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaIntegracion.ServicioProducto.Imagenes imagenes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public AgregarImagenProductoRequestBody() {
        }
        
        public AgregarImagenProductoRequestBody(CapaIntegracion.ServicioProducto.Imagenes imagenes, string Remitente, int Origen) {
            this.imagenes = imagenes;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarImagenProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarImagenProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioProducto.AgregarImagenProductoResponseBody Body;
        
        public AgregarImagenProductoResponse() {
        }
        
        public AgregarImagenProductoResponse(CapaIntegracion.ServicioProducto.AgregarImagenProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarImagenProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AgregarImagenProductoResult;
        
        public AgregarImagenProductoResponseBody() {
        }
        
        public AgregarImagenProductoResponseBody(bool AgregarImagenProductoResult) {
            this.AgregarImagenProductoResult = AgregarImagenProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerImagenesProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerImagenesProducto", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioProducto.ObtenerImagenesProductoRequestBody Body;
        
        public ObtenerImagenesProductoRequest() {
        }
        
        public ObtenerImagenesProductoRequest(CapaIntegracion.ServicioProducto.ObtenerImagenesProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerImagenesProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public ObtenerImagenesProductoRequestBody() {
        }
        
        public ObtenerImagenesProductoRequestBody(int ID, string Remitente, int Origen) {
            this.ID = ID;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerImagenesProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerImagenesProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioProducto.ObtenerImagenesProductoResponseBody Body;
        
        public ObtenerImagenesProductoResponse() {
        }
        
        public ObtenerImagenesProductoResponse(CapaIntegracion.ServicioProducto.ObtenerImagenesProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerImagenesProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerImagenesProductoResult;
        
        public ObtenerImagenesProductoResponseBody() {
        }
        
        public ObtenerImagenesProductoResponseBody(string ObtenerImagenesProductoResult) {
            this.ObtenerImagenesProductoResult = ObtenerImagenesProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarImagenPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarImagenP", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioProducto.EliminarImagenPRequestBody Body;
        
        public EliminarImagenPRequest() {
        }
        
        public EliminarImagenPRequest(CapaIntegracion.ServicioProducto.EliminarImagenPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarImagenPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NombreImagen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public EliminarImagenPRequestBody() {
        }
        
        public EliminarImagenPRequestBody(string NombreImagen, string Remitente, int Origen) {
            this.NombreImagen = NombreImagen;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarImagenPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarImagenPResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioProducto.EliminarImagenPResponseBody Body;
        
        public EliminarImagenPResponse() {
        }
        
        public EliminarImagenPResponse(CapaIntegracion.ServicioProducto.EliminarImagenPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarImagenPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaIntegracion.ServicioProducto.TaskOfBoolean EliminarImagenPResult;
        
        public EliminarImagenPResponseBody() {
        }
        
        public EliminarImagenPResponseBody(CapaIntegracion.ServicioProducto.TaskOfBoolean EliminarImagenPResult) {
            this.EliminarImagenPResult = EliminarImagenPResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioProductoSoapChannel : CapaIntegracion.ServicioProducto.ServicioProductoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioProductoSoapClient : System.ServiceModel.ClientBase<CapaIntegracion.ServicioProducto.ServicioProductoSoap>, CapaIntegracion.ServicioProducto.ServicioProductoSoap {
        
        public ServicioProductoSoapClient() {
        }
        
        public ServicioProductoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioProductoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProductoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProductoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaIntegracion.ServicioProducto.CrearProductoResponse CapaIntegracion.ServicioProducto.ServicioProductoSoap.CrearProducto(CapaIntegracion.ServicioProducto.CrearProductoRequest request) {
            return base.Channel.CrearProducto(request);
        }
        
        public bool CrearProducto(CapaIntegracion.ServicioProducto.Producto producto, string Remitente, int Origen) {
            CapaIntegracion.ServicioProducto.CrearProductoRequest inValue = new CapaIntegracion.ServicioProducto.CrearProductoRequest();
            inValue.Body = new CapaIntegracion.ServicioProducto.CrearProductoRequestBody();
            inValue.Body.producto = producto;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            CapaIntegracion.ServicioProducto.CrearProductoResponse retVal = ((CapaIntegracion.ServicioProducto.ServicioProductoSoap)(this)).CrearProducto(inValue);
            return retVal.Body.CrearProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.CrearProductoResponse> CapaIntegracion.ServicioProducto.ServicioProductoSoap.CrearProductoAsync(CapaIntegracion.ServicioProducto.CrearProductoRequest request) {
            return base.Channel.CrearProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.CrearProductoResponse> CrearProductoAsync(CapaIntegracion.ServicioProducto.Producto producto, string Remitente, int Origen) {
            CapaIntegracion.ServicioProducto.CrearProductoRequest inValue = new CapaIntegracion.ServicioProducto.CrearProductoRequest();
            inValue.Body = new CapaIntegracion.ServicioProducto.CrearProductoRequestBody();
            inValue.Body.producto = producto;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((CapaIntegracion.ServicioProducto.ServicioProductoSoap)(this)).CrearProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaIntegracion.ServicioProducto.ImagenesProductoResponse CapaIntegracion.ServicioProducto.ServicioProductoSoap.ImagenesProducto(CapaIntegracion.ServicioProducto.ImagenesProductoRequest request) {
            return base.Channel.ImagenesProducto(request);
        }
        
        public CapaIntegracion.ServicioProducto.Imagenes[] ImagenesProducto(int id, string Remitente, int Origen) {
            CapaIntegracion.ServicioProducto.ImagenesProductoRequest inValue = new CapaIntegracion.ServicioProducto.ImagenesProductoRequest();
            inValue.Body = new CapaIntegracion.ServicioProducto.ImagenesProductoRequestBody();
            inValue.Body.id = id;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            CapaIntegracion.ServicioProducto.ImagenesProductoResponse retVal = ((CapaIntegracion.ServicioProducto.ServicioProductoSoap)(this)).ImagenesProducto(inValue);
            return retVal.Body.ImagenesProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.ImagenesProductoResponse> CapaIntegracion.ServicioProducto.ServicioProductoSoap.ImagenesProductoAsync(CapaIntegracion.ServicioProducto.ImagenesProductoRequest request) {
            return base.Channel.ImagenesProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.ImagenesProductoResponse> ImagenesProductoAsync(int id, string Remitente, int Origen) {
            CapaIntegracion.ServicioProducto.ImagenesProductoRequest inValue = new CapaIntegracion.ServicioProducto.ImagenesProductoRequest();
            inValue.Body = new CapaIntegracion.ServicioProducto.ImagenesProductoRequestBody();
            inValue.Body.id = id;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((CapaIntegracion.ServicioProducto.ServicioProductoSoap)(this)).ImagenesProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaIntegracion.ServicioProducto.ProductoExisteResponse CapaIntegracion.ServicioProducto.ServicioProductoSoap.ProductoExiste(CapaIntegracion.ServicioProducto.ProductoExisteRequest request) {
            return base.Channel.ProductoExiste(request);
        }
        
        public bool ProductoExiste(string nombre, string Remitente, int Origen) {
            CapaIntegracion.ServicioProducto.ProductoExisteRequest inValue = new CapaIntegracion.ServicioProducto.ProductoExisteRequest();
            inValue.Body = new CapaIntegracion.ServicioProducto.ProductoExisteRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            CapaIntegracion.ServicioProducto.ProductoExisteResponse retVal = ((CapaIntegracion.ServicioProducto.ServicioProductoSoap)(this)).ProductoExiste(inValue);
            return retVal.Body.ProductoExisteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.ProductoExisteResponse> CapaIntegracion.ServicioProducto.ServicioProductoSoap.ProductoExisteAsync(CapaIntegracion.ServicioProducto.ProductoExisteRequest request) {
            return base.Channel.ProductoExisteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.ProductoExisteResponse> ProductoExisteAsync(string nombre, string Remitente, int Origen) {
            CapaIntegracion.ServicioProducto.ProductoExisteRequest inValue = new CapaIntegracion.ServicioProducto.ProductoExisteRequest();
            inValue.Body = new CapaIntegracion.ServicioProducto.ProductoExisteRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((CapaIntegracion.ServicioProducto.ServicioProductoSoap)(this)).ProductoExisteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaIntegracion.ServicioProducto.ComandoProductosResponse CapaIntegracion.ServicioProducto.ServicioProductoSoap.ComandoProductos(CapaIntegracion.ServicioProducto.ComandoProductosRequest request) {
            return base.Channel.ComandoProductos(request);
        }
        
        public string ComandoProductos(int Orden, string Remitente, int Origen) {
            CapaIntegracion.ServicioProducto.ComandoProductosRequest inValue = new CapaIntegracion.ServicioProducto.ComandoProductosRequest();
            inValue.Body = new CapaIntegracion.ServicioProducto.ComandoProductosRequestBody();
            inValue.Body.Orden = Orden;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            CapaIntegracion.ServicioProducto.ComandoProductosResponse retVal = ((CapaIntegracion.ServicioProducto.ServicioProductoSoap)(this)).ComandoProductos(inValue);
            return retVal.Body.ComandoProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.ComandoProductosResponse> CapaIntegracion.ServicioProducto.ServicioProductoSoap.ComandoProductosAsync(CapaIntegracion.ServicioProducto.ComandoProductosRequest request) {
            return base.Channel.ComandoProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.ComandoProductosResponse> ComandoProductosAsync(int Orden, string Remitente, int Origen) {
            CapaIntegracion.ServicioProducto.ComandoProductosRequest inValue = new CapaIntegracion.ServicioProducto.ComandoProductosRequest();
            inValue.Body = new CapaIntegracion.ServicioProducto.ComandoProductosRequestBody();
            inValue.Body.Orden = Orden;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((CapaIntegracion.ServicioProducto.ServicioProductoSoap)(this)).ComandoProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaIntegracion.ServicioProducto.ActualizarProductoResponse CapaIntegracion.ServicioProducto.ServicioProductoSoap.ActualizarProducto(CapaIntegracion.ServicioProducto.ActualizarProductoRequest request) {
            return base.Channel.ActualizarProducto(request);
        }
        
        public bool ActualizarProducto(CapaIntegracion.ServicioProducto.Producto producto, string Remitente, int Origen) {
            CapaIntegracion.ServicioProducto.ActualizarProductoRequest inValue = new CapaIntegracion.ServicioProducto.ActualizarProductoRequest();
            inValue.Body = new CapaIntegracion.ServicioProducto.ActualizarProductoRequestBody();
            inValue.Body.producto = producto;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            CapaIntegracion.ServicioProducto.ActualizarProductoResponse retVal = ((CapaIntegracion.ServicioProducto.ServicioProductoSoap)(this)).ActualizarProducto(inValue);
            return retVal.Body.ActualizarProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.ActualizarProductoResponse> CapaIntegracion.ServicioProducto.ServicioProductoSoap.ActualizarProductoAsync(CapaIntegracion.ServicioProducto.ActualizarProductoRequest request) {
            return base.Channel.ActualizarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.ActualizarProductoResponse> ActualizarProductoAsync(CapaIntegracion.ServicioProducto.Producto producto, string Remitente, int Origen) {
            CapaIntegracion.ServicioProducto.ActualizarProductoRequest inValue = new CapaIntegracion.ServicioProducto.ActualizarProductoRequest();
            inValue.Body = new CapaIntegracion.ServicioProducto.ActualizarProductoRequestBody();
            inValue.Body.producto = producto;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((CapaIntegracion.ServicioProducto.ServicioProductoSoap)(this)).ActualizarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaIntegracion.ServicioProducto.EliminarProductoResponse CapaIntegracion.ServicioProducto.ServicioProductoSoap.EliminarProducto(CapaIntegracion.ServicioProducto.EliminarProductoRequest request) {
            return base.Channel.EliminarProducto(request);
        }
        
        public bool EliminarProducto(int Id, string Remitente, int Origen) {
            CapaIntegracion.ServicioProducto.EliminarProductoRequest inValue = new CapaIntegracion.ServicioProducto.EliminarProductoRequest();
            inValue.Body = new CapaIntegracion.ServicioProducto.EliminarProductoRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            CapaIntegracion.ServicioProducto.EliminarProductoResponse retVal = ((CapaIntegracion.ServicioProducto.ServicioProductoSoap)(this)).EliminarProducto(inValue);
            return retVal.Body.EliminarProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.EliminarProductoResponse> CapaIntegracion.ServicioProducto.ServicioProductoSoap.EliminarProductoAsync(CapaIntegracion.ServicioProducto.EliminarProductoRequest request) {
            return base.Channel.EliminarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.EliminarProductoResponse> EliminarProductoAsync(int Id, string Remitente, int Origen) {
            CapaIntegracion.ServicioProducto.EliminarProductoRequest inValue = new CapaIntegracion.ServicioProducto.EliminarProductoRequest();
            inValue.Body = new CapaIntegracion.ServicioProducto.EliminarProductoRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((CapaIntegracion.ServicioProducto.ServicioProductoSoap)(this)).EliminarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaIntegracion.ServicioProducto.AgregarImagenProductoResponse CapaIntegracion.ServicioProducto.ServicioProductoSoap.AgregarImagenProducto(CapaIntegracion.ServicioProducto.AgregarImagenProductoRequest request) {
            return base.Channel.AgregarImagenProducto(request);
        }
        
        public bool AgregarImagenProducto(CapaIntegracion.ServicioProducto.Imagenes imagenes, string Remitente, int Origen) {
            CapaIntegracion.ServicioProducto.AgregarImagenProductoRequest inValue = new CapaIntegracion.ServicioProducto.AgregarImagenProductoRequest();
            inValue.Body = new CapaIntegracion.ServicioProducto.AgregarImagenProductoRequestBody();
            inValue.Body.imagenes = imagenes;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            CapaIntegracion.ServicioProducto.AgregarImagenProductoResponse retVal = ((CapaIntegracion.ServicioProducto.ServicioProductoSoap)(this)).AgregarImagenProducto(inValue);
            return retVal.Body.AgregarImagenProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.AgregarImagenProductoResponse> CapaIntegracion.ServicioProducto.ServicioProductoSoap.AgregarImagenProductoAsync(CapaIntegracion.ServicioProducto.AgregarImagenProductoRequest request) {
            return base.Channel.AgregarImagenProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.AgregarImagenProductoResponse> AgregarImagenProductoAsync(CapaIntegracion.ServicioProducto.Imagenes imagenes, string Remitente, int Origen) {
            CapaIntegracion.ServicioProducto.AgregarImagenProductoRequest inValue = new CapaIntegracion.ServicioProducto.AgregarImagenProductoRequest();
            inValue.Body = new CapaIntegracion.ServicioProducto.AgregarImagenProductoRequestBody();
            inValue.Body.imagenes = imagenes;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((CapaIntegracion.ServicioProducto.ServicioProductoSoap)(this)).AgregarImagenProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaIntegracion.ServicioProducto.ObtenerImagenesProductoResponse CapaIntegracion.ServicioProducto.ServicioProductoSoap.ObtenerImagenesProducto(CapaIntegracion.ServicioProducto.ObtenerImagenesProductoRequest request) {
            return base.Channel.ObtenerImagenesProducto(request);
        }
        
        public string ObtenerImagenesProducto(int ID, string Remitente, int Origen) {
            CapaIntegracion.ServicioProducto.ObtenerImagenesProductoRequest inValue = new CapaIntegracion.ServicioProducto.ObtenerImagenesProductoRequest();
            inValue.Body = new CapaIntegracion.ServicioProducto.ObtenerImagenesProductoRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            CapaIntegracion.ServicioProducto.ObtenerImagenesProductoResponse retVal = ((CapaIntegracion.ServicioProducto.ServicioProductoSoap)(this)).ObtenerImagenesProducto(inValue);
            return retVal.Body.ObtenerImagenesProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.ObtenerImagenesProductoResponse> CapaIntegracion.ServicioProducto.ServicioProductoSoap.ObtenerImagenesProductoAsync(CapaIntegracion.ServicioProducto.ObtenerImagenesProductoRequest request) {
            return base.Channel.ObtenerImagenesProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.ObtenerImagenesProductoResponse> ObtenerImagenesProductoAsync(int ID, string Remitente, int Origen) {
            CapaIntegracion.ServicioProducto.ObtenerImagenesProductoRequest inValue = new CapaIntegracion.ServicioProducto.ObtenerImagenesProductoRequest();
            inValue.Body = new CapaIntegracion.ServicioProducto.ObtenerImagenesProductoRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((CapaIntegracion.ServicioProducto.ServicioProductoSoap)(this)).ObtenerImagenesProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaIntegracion.ServicioProducto.EliminarImagenPResponse CapaIntegracion.ServicioProducto.ServicioProductoSoap.EliminarImagenP(CapaIntegracion.ServicioProducto.EliminarImagenPRequest request) {
            return base.Channel.EliminarImagenP(request);
        }
        
        public CapaIntegracion.ServicioProducto.TaskOfBoolean EliminarImagenP(string NombreImagen, string Remitente, int Origen) {
            CapaIntegracion.ServicioProducto.EliminarImagenPRequest inValue = new CapaIntegracion.ServicioProducto.EliminarImagenPRequest();
            inValue.Body = new CapaIntegracion.ServicioProducto.EliminarImagenPRequestBody();
            inValue.Body.NombreImagen = NombreImagen;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            CapaIntegracion.ServicioProducto.EliminarImagenPResponse retVal = ((CapaIntegracion.ServicioProducto.ServicioProductoSoap)(this)).EliminarImagenP(inValue);
            return retVal.Body.EliminarImagenPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.EliminarImagenPResponse> CapaIntegracion.ServicioProducto.ServicioProductoSoap.EliminarImagenPAsync(CapaIntegracion.ServicioProducto.EliminarImagenPRequest request) {
            return base.Channel.EliminarImagenPAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.ServicioProducto.EliminarImagenPResponse> EliminarImagenPAsync(string NombreImagen, string Remitente, int Origen) {
            CapaIntegracion.ServicioProducto.EliminarImagenPRequest inValue = new CapaIntegracion.ServicioProducto.EliminarImagenPRequest();
            inValue.Body = new CapaIntegracion.ServicioProducto.EliminarImagenPRequestBody();
            inValue.Body.NombreImagen = NombreImagen;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((CapaIntegracion.ServicioProducto.ServicioProductoSoap)(this)).EliminarImagenPAsync(inValue);
        }
    }
}
