//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaIntegracion.ServicioMarca {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Marca", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Marca : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Logo {
            get {
                return this.LogoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoField, value) != true)) {
                    this.LogoField = value;
                    this.RaisePropertyChanged("Logo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioMarca.ServicioMarcaSoap")]
    public interface ServicioMarcaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento marca del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarMarca", ReplyAction="*")]
        CapaIntegracion.ServicioMarca.AgregarMarcaResponse AgregarMarca(CapaIntegracion.ServicioMarca.AgregarMarcaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarMarca", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioMarca.AgregarMarcaResponse> AgregarMarcaAsync(CapaIntegracion.ServicioMarca.AgregarMarcaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Remitente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerMarca", ReplyAction="*")]
        CapaIntegracion.ServicioMarca.ObtenerMarcaResponse ObtenerMarca(CapaIntegracion.ServicioMarca.ObtenerMarcaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerMarca", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioMarca.ObtenerMarcaResponse> ObtenerMarcaAsync(CapaIntegracion.ServicioMarca.ObtenerMarcaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento marca del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarMarca", ReplyAction="*")]
        CapaIntegracion.ServicioMarca.ActualizarMarcaResponse ActualizarMarca(CapaIntegracion.ServicioMarca.ActualizarMarcaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarMarca", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioMarca.ActualizarMarcaResponse> ActualizarMarcaAsync(CapaIntegracion.ServicioMarca.ActualizarMarcaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Remitente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarMarca", ReplyAction="*")]
        CapaIntegracion.ServicioMarca.EliminarMarcaResponse EliminarMarca(CapaIntegracion.ServicioMarca.EliminarMarcaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarMarca", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioMarca.EliminarMarcaResponse> EliminarMarcaAsync(CapaIntegracion.ServicioMarca.EliminarMarcaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarMarcaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarMarca", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioMarca.AgregarMarcaRequestBody Body;
        
        public AgregarMarcaRequest() {
        }
        
        public AgregarMarcaRequest(CapaIntegracion.ServicioMarca.AgregarMarcaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarMarcaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaIntegracion.ServicioMarca.Marca marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public AgregarMarcaRequestBody() {
        }
        
        public AgregarMarcaRequestBody(CapaIntegracion.ServicioMarca.Marca marca, string Remitente, int Origen) {
            this.marca = marca;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarMarcaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarMarcaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioMarca.AgregarMarcaResponseBody Body;
        
        public AgregarMarcaResponse() {
        }
        
        public AgregarMarcaResponse(CapaIntegracion.ServicioMarca.AgregarMarcaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarMarcaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AgregarMarcaResult;
        
        public AgregarMarcaResponseBody() {
        }
        
        public AgregarMarcaResponseBody(bool AgregarMarcaResult) {
            this.AgregarMarcaResult = AgregarMarcaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerMarcaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerMarca", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioMarca.ObtenerMarcaRequestBody Body;
        
        public ObtenerMarcaRequest() {
        }
        
        public ObtenerMarcaRequest(CapaIntegracion.ServicioMarca.ObtenerMarcaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerMarcaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Origen;
        
        public ObtenerMarcaRequestBody() {
        }
        
        public ObtenerMarcaRequestBody(string Remitente, int Origen) {
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerMarcaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerMarcaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioMarca.ObtenerMarcaResponseBody Body;
        
        public ObtenerMarcaResponse() {
        }
        
        public ObtenerMarcaResponse(CapaIntegracion.ServicioMarca.ObtenerMarcaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerMarcaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerMarcaResult;
        
        public ObtenerMarcaResponseBody() {
        }
        
        public ObtenerMarcaResponseBody(string ObtenerMarcaResult) {
            this.ObtenerMarcaResult = ObtenerMarcaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarMarcaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarMarca", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioMarca.ActualizarMarcaRequestBody Body;
        
        public ActualizarMarcaRequest() {
        }
        
        public ActualizarMarcaRequest(CapaIntegracion.ServicioMarca.ActualizarMarcaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarMarcaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaIntegracion.ServicioMarca.Marca marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public ActualizarMarcaRequestBody() {
        }
        
        public ActualizarMarcaRequestBody(CapaIntegracion.ServicioMarca.Marca marca, string Remitente, int Origen) {
            this.marca = marca;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarMarcaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarMarcaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioMarca.ActualizarMarcaResponseBody Body;
        
        public ActualizarMarcaResponse() {
        }
        
        public ActualizarMarcaResponse(CapaIntegracion.ServicioMarca.ActualizarMarcaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarMarcaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarMarcaResult;
        
        public ActualizarMarcaResponseBody() {
        }
        
        public ActualizarMarcaResponseBody(bool ActualizarMarcaResult) {
            this.ActualizarMarcaResult = ActualizarMarcaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarMarcaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarMarca", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioMarca.EliminarMarcaRequestBody Body;
        
        public EliminarMarcaRequest() {
        }
        
        public EliminarMarcaRequest(CapaIntegracion.ServicioMarca.EliminarMarcaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarMarcaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public EliminarMarcaRequestBody() {
        }
        
        public EliminarMarcaRequestBody(int Id, string Remitente, int Origen) {
            this.Id = Id;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarMarcaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarMarcaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioMarca.EliminarMarcaResponseBody Body;
        
        public EliminarMarcaResponse() {
        }
        
        public EliminarMarcaResponse(CapaIntegracion.ServicioMarca.EliminarMarcaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarMarcaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EliminarMarcaResult;
        
        public EliminarMarcaResponseBody() {
        }
        
        public EliminarMarcaResponseBody(bool EliminarMarcaResult) {
            this.EliminarMarcaResult = EliminarMarcaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioMarcaSoapChannel : CapaIntegracion.ServicioMarca.ServicioMarcaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioMarcaSoapClient : System.ServiceModel.ClientBase<CapaIntegracion.ServicioMarca.ServicioMarcaSoap>, CapaIntegracion.ServicioMarca.ServicioMarcaSoap {
        
        public ServicioMarcaSoapClient() {
        }
        
        public ServicioMarcaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioMarcaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioMarcaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioMarcaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaIntegracion.ServicioMarca.AgregarMarcaResponse CapaIntegracion.ServicioMarca.ServicioMarcaSoap.AgregarMarca(CapaIntegracion.ServicioMarca.AgregarMarcaRequest request) {
            return base.Channel.AgregarMarca(request);
        }
        
        public bool AgregarMarca(CapaIntegracion.ServicioMarca.Marca marca, string Remitente, int Origen) {
            CapaIntegracion.ServicioMarca.AgregarMarcaRequest inValue = new CapaIntegracion.ServicioMarca.AgregarMarcaRequest();
            inValue.Body = new CapaIntegracion.ServicioMarca.AgregarMarcaRequestBody();
            inValue.Body.marca = marca;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            CapaIntegracion.ServicioMarca.AgregarMarcaResponse retVal = ((CapaIntegracion.ServicioMarca.ServicioMarcaSoap)(this)).AgregarMarca(inValue);
            return retVal.Body.AgregarMarcaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioMarca.AgregarMarcaResponse> CapaIntegracion.ServicioMarca.ServicioMarcaSoap.AgregarMarcaAsync(CapaIntegracion.ServicioMarca.AgregarMarcaRequest request) {
            return base.Channel.AgregarMarcaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.ServicioMarca.AgregarMarcaResponse> AgregarMarcaAsync(CapaIntegracion.ServicioMarca.Marca marca, string Remitente, int Origen) {
            CapaIntegracion.ServicioMarca.AgregarMarcaRequest inValue = new CapaIntegracion.ServicioMarca.AgregarMarcaRequest();
            inValue.Body = new CapaIntegracion.ServicioMarca.AgregarMarcaRequestBody();
            inValue.Body.marca = marca;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((CapaIntegracion.ServicioMarca.ServicioMarcaSoap)(this)).AgregarMarcaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaIntegracion.ServicioMarca.ObtenerMarcaResponse CapaIntegracion.ServicioMarca.ServicioMarcaSoap.ObtenerMarca(CapaIntegracion.ServicioMarca.ObtenerMarcaRequest request) {
            return base.Channel.ObtenerMarca(request);
        }
        
        public string ObtenerMarca(string Remitente, int Origen) {
            CapaIntegracion.ServicioMarca.ObtenerMarcaRequest inValue = new CapaIntegracion.ServicioMarca.ObtenerMarcaRequest();
            inValue.Body = new CapaIntegracion.ServicioMarca.ObtenerMarcaRequestBody();
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            CapaIntegracion.ServicioMarca.ObtenerMarcaResponse retVal = ((CapaIntegracion.ServicioMarca.ServicioMarcaSoap)(this)).ObtenerMarca(inValue);
            return retVal.Body.ObtenerMarcaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioMarca.ObtenerMarcaResponse> CapaIntegracion.ServicioMarca.ServicioMarcaSoap.ObtenerMarcaAsync(CapaIntegracion.ServicioMarca.ObtenerMarcaRequest request) {
            return base.Channel.ObtenerMarcaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.ServicioMarca.ObtenerMarcaResponse> ObtenerMarcaAsync(string Remitente, int Origen) {
            CapaIntegracion.ServicioMarca.ObtenerMarcaRequest inValue = new CapaIntegracion.ServicioMarca.ObtenerMarcaRequest();
            inValue.Body = new CapaIntegracion.ServicioMarca.ObtenerMarcaRequestBody();
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((CapaIntegracion.ServicioMarca.ServicioMarcaSoap)(this)).ObtenerMarcaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaIntegracion.ServicioMarca.ActualizarMarcaResponse CapaIntegracion.ServicioMarca.ServicioMarcaSoap.ActualizarMarca(CapaIntegracion.ServicioMarca.ActualizarMarcaRequest request) {
            return base.Channel.ActualizarMarca(request);
        }
        
        public bool ActualizarMarca(CapaIntegracion.ServicioMarca.Marca marca, string Remitente, int Origen) {
            CapaIntegracion.ServicioMarca.ActualizarMarcaRequest inValue = new CapaIntegracion.ServicioMarca.ActualizarMarcaRequest();
            inValue.Body = new CapaIntegracion.ServicioMarca.ActualizarMarcaRequestBody();
            inValue.Body.marca = marca;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            CapaIntegracion.ServicioMarca.ActualizarMarcaResponse retVal = ((CapaIntegracion.ServicioMarca.ServicioMarcaSoap)(this)).ActualizarMarca(inValue);
            return retVal.Body.ActualizarMarcaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioMarca.ActualizarMarcaResponse> CapaIntegracion.ServicioMarca.ServicioMarcaSoap.ActualizarMarcaAsync(CapaIntegracion.ServicioMarca.ActualizarMarcaRequest request) {
            return base.Channel.ActualizarMarcaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.ServicioMarca.ActualizarMarcaResponse> ActualizarMarcaAsync(CapaIntegracion.ServicioMarca.Marca marca, string Remitente, int Origen) {
            CapaIntegracion.ServicioMarca.ActualizarMarcaRequest inValue = new CapaIntegracion.ServicioMarca.ActualizarMarcaRequest();
            inValue.Body = new CapaIntegracion.ServicioMarca.ActualizarMarcaRequestBody();
            inValue.Body.marca = marca;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((CapaIntegracion.ServicioMarca.ServicioMarcaSoap)(this)).ActualizarMarcaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaIntegracion.ServicioMarca.EliminarMarcaResponse CapaIntegracion.ServicioMarca.ServicioMarcaSoap.EliminarMarca(CapaIntegracion.ServicioMarca.EliminarMarcaRequest request) {
            return base.Channel.EliminarMarca(request);
        }
        
        public bool EliminarMarca(int Id, string Remitente, int Origen) {
            CapaIntegracion.ServicioMarca.EliminarMarcaRequest inValue = new CapaIntegracion.ServicioMarca.EliminarMarcaRequest();
            inValue.Body = new CapaIntegracion.ServicioMarca.EliminarMarcaRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            CapaIntegracion.ServicioMarca.EliminarMarcaResponse retVal = ((CapaIntegracion.ServicioMarca.ServicioMarcaSoap)(this)).EliminarMarca(inValue);
            return retVal.Body.EliminarMarcaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioMarca.EliminarMarcaResponse> CapaIntegracion.ServicioMarca.ServicioMarcaSoap.EliminarMarcaAsync(CapaIntegracion.ServicioMarca.EliminarMarcaRequest request) {
            return base.Channel.EliminarMarcaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.ServicioMarca.EliminarMarcaResponse> EliminarMarcaAsync(int Id, string Remitente, int Origen) {
            CapaIntegracion.ServicioMarca.EliminarMarcaRequest inValue = new CapaIntegracion.ServicioMarca.EliminarMarcaRequest();
            inValue.Body = new CapaIntegracion.ServicioMarca.EliminarMarcaRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((CapaIntegracion.ServicioMarca.ServicioMarcaSoap)(this)).EliminarMarcaAsync(inValue);
        }
    }
}
