//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaIntegracion.ServicioGenerales {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioGenerales.ServicioGeneralesSoap")]
    public interface ServicioGeneralesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento archivoB del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubirImagen", ReplyAction="*")]
        CapaIntegracion.ServicioGenerales.SubirImagenResponse SubirImagen(CapaIntegracion.ServicioGenerales.SubirImagenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubirImagen", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioGenerales.SubirImagenResponse> SubirImagenAsync(CapaIntegracion.ServicioGenerales.SubirImagenRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImagenExiste", ReplyAction="*")]
        CapaIntegracion.ServicioGenerales.ImagenExisteResponse ImagenExiste(CapaIntegracion.ServicioGenerales.ImagenExisteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImagenExiste", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioGenerales.ImagenExisteResponse> ImagenExisteAsync(CapaIntegracion.ServicioGenerales.ImagenExisteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubirImagenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubirImagen", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioGenerales.SubirImagenRequestBody Body;
        
        public SubirImagenRequest() {
        }
        
        public SubirImagenRequest(CapaIntegracion.ServicioGenerales.SubirImagenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubirImagenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orden;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] archivoB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Origen;
        
        public SubirImagenRequestBody() {
        }
        
        public SubirImagenRequestBody(int orden, byte[] archivoB, string nombre, string Remitente, int Origen) {
            this.orden = orden;
            this.archivoB = archivoB;
            this.nombre = nombre;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubirImagenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubirImagenResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioGenerales.SubirImagenResponseBody Body;
        
        public SubirImagenResponse() {
        }
        
        public SubirImagenResponse(CapaIntegracion.ServicioGenerales.SubirImagenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubirImagenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubirImagenResult;
        
        public SubirImagenResponseBody() {
        }
        
        public SubirImagenResponseBody(string SubirImagenResult) {
            this.SubirImagenResult = SubirImagenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImagenExisteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImagenExiste", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioGenerales.ImagenExisteRequestBody Body;
        
        public ImagenExisteRequest() {
        }
        
        public ImagenExisteRequest(CapaIntegracion.ServicioGenerales.ImagenExisteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImagenExisteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public ImagenExisteRequestBody() {
        }
        
        public ImagenExisteRequestBody(string nombre, string Remitente, int Origen) {
            this.nombre = nombre;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImagenExisteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImagenExisteResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaIntegracion.ServicioGenerales.ImagenExisteResponseBody Body;
        
        public ImagenExisteResponse() {
        }
        
        public ImagenExisteResponse(CapaIntegracion.ServicioGenerales.ImagenExisteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImagenExisteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ImagenExisteResult;
        
        public ImagenExisteResponseBody() {
        }
        
        public ImagenExisteResponseBody(bool ImagenExisteResult) {
            this.ImagenExisteResult = ImagenExisteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioGeneralesSoapChannel : CapaIntegracion.ServicioGenerales.ServicioGeneralesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioGeneralesSoapClient : System.ServiceModel.ClientBase<CapaIntegracion.ServicioGenerales.ServicioGeneralesSoap>, CapaIntegracion.ServicioGenerales.ServicioGeneralesSoap {
        
        public ServicioGeneralesSoapClient() {
        }
        
        public ServicioGeneralesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioGeneralesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGeneralesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGeneralesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaIntegracion.ServicioGenerales.SubirImagenResponse CapaIntegracion.ServicioGenerales.ServicioGeneralesSoap.SubirImagen(CapaIntegracion.ServicioGenerales.SubirImagenRequest request) {
            return base.Channel.SubirImagen(request);
        }
        
        public string SubirImagen(int orden, byte[] archivoB, string nombre, string Remitente, int Origen) {
            CapaIntegracion.ServicioGenerales.SubirImagenRequest inValue = new CapaIntegracion.ServicioGenerales.SubirImagenRequest();
            inValue.Body = new CapaIntegracion.ServicioGenerales.SubirImagenRequestBody();
            inValue.Body.orden = orden;
            inValue.Body.archivoB = archivoB;
            inValue.Body.nombre = nombre;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            CapaIntegracion.ServicioGenerales.SubirImagenResponse retVal = ((CapaIntegracion.ServicioGenerales.ServicioGeneralesSoap)(this)).SubirImagen(inValue);
            return retVal.Body.SubirImagenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioGenerales.SubirImagenResponse> CapaIntegracion.ServicioGenerales.ServicioGeneralesSoap.SubirImagenAsync(CapaIntegracion.ServicioGenerales.SubirImagenRequest request) {
            return base.Channel.SubirImagenAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.ServicioGenerales.SubirImagenResponse> SubirImagenAsync(int orden, byte[] archivoB, string nombre, string Remitente, int Origen) {
            CapaIntegracion.ServicioGenerales.SubirImagenRequest inValue = new CapaIntegracion.ServicioGenerales.SubirImagenRequest();
            inValue.Body = new CapaIntegracion.ServicioGenerales.SubirImagenRequestBody();
            inValue.Body.orden = orden;
            inValue.Body.archivoB = archivoB;
            inValue.Body.nombre = nombre;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((CapaIntegracion.ServicioGenerales.ServicioGeneralesSoap)(this)).SubirImagenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaIntegracion.ServicioGenerales.ImagenExisteResponse CapaIntegracion.ServicioGenerales.ServicioGeneralesSoap.ImagenExiste(CapaIntegracion.ServicioGenerales.ImagenExisteRequest request) {
            return base.Channel.ImagenExiste(request);
        }
        
        public bool ImagenExiste(string nombre, string Remitente, int Origen) {
            CapaIntegracion.ServicioGenerales.ImagenExisteRequest inValue = new CapaIntegracion.ServicioGenerales.ImagenExisteRequest();
            inValue.Body = new CapaIntegracion.ServicioGenerales.ImagenExisteRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            CapaIntegracion.ServicioGenerales.ImagenExisteResponse retVal = ((CapaIntegracion.ServicioGenerales.ServicioGeneralesSoap)(this)).ImagenExiste(inValue);
            return retVal.Body.ImagenExisteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaIntegracion.ServicioGenerales.ImagenExisteResponse> CapaIntegracion.ServicioGenerales.ServicioGeneralesSoap.ImagenExisteAsync(CapaIntegracion.ServicioGenerales.ImagenExisteRequest request) {
            return base.Channel.ImagenExisteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.ServicioGenerales.ImagenExisteResponse> ImagenExisteAsync(string nombre, string Remitente, int Origen) {
            CapaIntegracion.ServicioGenerales.ImagenExisteRequest inValue = new CapaIntegracion.ServicioGenerales.ImagenExisteRequest();
            inValue.Body = new CapaIntegracion.ServicioGenerales.ImagenExisteRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((CapaIntegracion.ServicioGenerales.ServicioGeneralesSoap)(this)).ImagenExisteAsync(inValue);
        }
    }
}
